### ISSUE TITLE
JOSS: paper 

### ISSUE THREAD

**Issue by bonh** [JanLeppert/GasChromatographySimulator.jl#46]
In reference to https://github.com/openjournals/joss-reviews/issues/4565.

I will post issues and questions about the paper here and hope that we can engage in a discussion about them.

**Comment by bonh** [comment]
Summary: There are a lot of brackets which makes it hard for me to follow. Are they really necessary at that stage?

Statement of need: I think some of the more practical parts in the summary might be better suited in the statement of need. Why gas chromatography? Why simulation of it? And I'm missing "who the target audience is, and its relation to other work".

**Comment by bonh** [comment]
And perhaps you could "mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it."

**Comment by JanLeppert** [comment]
Thank you for your comments. I agree with your notes and I will make some changes to the text in the next days. I also will make some small changes to the documentation due to some updates of the package.

**Comment by bonh** [comment]
I think you should "indicate whether related publications (published, in review, or nearing submission) exist as part of submitting to JOSS", see link above. In my opinion, the paper and this submission are both valuable but perhaps you would like to mention the paper more prominently in your JOSS paper (already in the summary?).

**Comment by bonh** [comment]
To produce the results of the paper http://10.0.3.248/j.chroma.2020.460985 did you use a predecessor or even an early version of GasChromatographySimulator.jl? If you did it might make sense to use that paper to provide validating results of your software. Otherwise you might want to add a plot to the JOSS paper indicating what kind of results including their accuracy one can expect from your software.

**Comment by JanLeppert** [comment]
In the paper was a predecessor used, written in Scilab (similar to Matlab). The fundamental models for fluidics and retention are the same. The Scilab version used a simpler approach to solve the ODE (in principal the Euler method), which toke much more time to run. 

I started to implement two examples from this paper (one with conventional GC, one with thermal gradient) in the documentation (#55). I have thought about this earlier. I could than add a plot from these examples (e.g. comparison of measured and simulated chromatograms)

**Comment by JanLeppert** [comment]
In regards to related publications:
- The previous publication [doi.org/10.1016/j.chroma.2021.461943](https://doi.org/10.1016/j.chroma.2021.461943) uses another model (a much more idealized model of chromatography), but in principal uses the same solving of ODEs. For this publication I made the Github project [IBSpublic](https://github.com/JanLeppert/IBSpublic)
- I have some publications in preparation, but they still will take some time
- Based on GasChromatographySimulator.jl I work on two additional packages. One which uses the simulation to calculate the 3 thermodynamic retention parameters of the substances from a handful of temperature programmed measurements using optimization (for this I have a rough prototype, but not yet tested with real data and not optimized). In another project I will use the GasChromatographySimulator.jl to simulate complex GC-systems with multiple GC-columns, e.g. GCxGC, GCxGCxGC, splitting between multiple columns, ... (but this is still in a very early stage)

**Comment by JanLeppert** [comment]
With #59 I re-worked the draft of the paper.

I changed the order of paragraphs, moved some from section **Summary** to **Statement of need**.

I added a graph, where a measured chromatogram (taken from [10.1016/j.chroma.2020.460985](http://10.0.3.248/j.chroma.2020.460985)) is compared with a simulation. Two comparisons are now part of the documentation in section **Examples**.

I added a paragraph about similar software (lines 55-60) and added another paragraph about related work/projects (line 61-65)
