### ISSUE TITLE
JOSS REVIEW: Add community guidelines

### ISSUE THREAD

**Issue by ma-sadeghi** [JanLeppert/GasChromatographySimulator.jl#50]
I might have missed them, but I couldn't find any community guidelines (how to seek support, where to file issues/bugs, how to contribute to the software). You could probably add a separate section called "Community Guidelines" to the README.

**Comment by JanLeppert** [comment]
With #55 I added a CONTRIBUTING.md.

**Comment by bonh** [comment]
Did you add this info to the documentation too? I think that would be helpful.

**Comment by JanLeppert** [comment]
With #63 I also added a section `Contribution` to the `README.md`.

**Comment by JanLeppert** [comment]
I also added a section `Contribution` to the first page of the documentation (`dev` version)
