### ISSUE TITLE
JOSS REVIEW: Namespace a little too polluted?

### ISSUE THREAD

**Issue by ma-sadeghi** [JanLeppert/GasChromatographySimulator.jl#53]
When importing `GasChromotographySimulator`, the namespace gets polluted with DifferentialEquations.jl exported functions (and other packages probably). Is this really needed?

PS. This is more of a recommendation, so if you feel like exporting everything, feel free to do it and close this issue.

**Comment by JanLeppert** [comment]
Thank you for the hint. I only need the solver methods exported, which I normally use. I changed the reexport for just these three functions.
