### ISSUE TITLE
JOSS Review: notebooks

### ISSUE THREAD

**Issue by bonh** [JanLeppert/GasChromatographySimulator.jl#62]
Not sure if I am doing something fundamentally wrong but executing the notebook `simulation_conventional_GC.jl` does result in `UndefVarError: DataFrame not defined`.

**Comment by bonh** [comment]
That's odd; I cannot really see what is failing...perhaps my local config is faulty.

**Comment by bonh** [comment]
Ohhh, it was already missing at the top.

**Comment by bonh** [comment]
yea, it seems like it's missing from all the examples?

**Comment by JanLeppert** [comment]
yes, I forgot to update the notebooks, after I changed the reexport (#53). I will change the notebooks and test them.

**Comment by JanLeppert** [comment]
With #64 I updated and checked the notebooks. They should work now.

**Comment by JanLeppert** [comment]
Perhaps I could include the notebooks in the `runtests.jl`?

**Comment by bonh** [comment]
If you want to include the notebooks as tests go ahead. But this does not concern my recommendation for publication in JOSS so I will close this issue.
