### ISSUE TITLE
JOSS REVIEW: references to software packages

### ISSUE THREAD

**Issue by bonh** [JanLeppert/GasChromatographySimulator.jl#65]
In the documentation:
> The simulation uses the following packages:
[OrdinaryDiffEq.jl](https://github.com/SciML/OrdinaryDiffEq.jl) part of [DifferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl)
[Interpolations.jl](https://github.com/JuliaMath/Interpolations.jl)
[Integrals.jl](https://github.com/SciML/Integrals.jl)
[ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl)
[ChemicalIdentifiers.jl](https://github.com/longemen3000/ChemicalIdentifiers.jl)
[Pluto.jl](https://github.com/fonsp/Pluto.jl)

Some of these packages provide notes on how to cite them, e.g., https://diffeq.sciml.ai/latest/#Supporting-and-Citing. 

In the paper, you are only citing Julia and Pluto. I am not sure wether it makes sense to add more references to the paper.

**Comment by JanLeppert** [comment]
The citation for `DifferentialEquations.jl` was already in the paper (Rackauckas & Nie, 2017), but I updated naming the used packages (lines 39 to 41) and added the citation for `ForwardDiff.jl` (Revels et al., 2016). For `Interpolations.jl` and `ChemicalIdentifiers.jl` no citation is available.
